import {
  AdminLoginTokenStatus,
  ActivityLogType,
  AuditAction,
  DeliveryStatus,
  DiscountType,
  InventoryStatus,
  NotificationType,
  OrderStatus,
  PaymentStatus,
  RoleName,
  TicketStatus,
  UserStatus,
} from './admin-enums.model';
import { AdminEntityConfig, AdminEnumOption } from '../interfaces/admin-crud.interface';

const enumOptions = (source: Record<string, string | number>): AdminEnumOption[] =>
  Object.entries(source)
    .filter(([label]) => Number.isNaN(Number(label)))
    .map(([label, value]) => ({ label, value }));

const timestamps = [
  { name: 'createdAt', label: 'Created at', type: 'date' as const, readonly: true, list: true, create: false, update: false },
  { name: 'updatedAt', label: 'Updated at', type: 'date' as const, readonly: true, list: true, create: false, update: false },
];

const softDeleteField = {
  name: 'isDeleted',
  label: 'Deleted',
  type: 'boolean' as const,
  readonly: true,
  hidden: true,
  create: false,
  update: false,
};

export const ADMIN_ENTITIES: AdminEntityConfig[] = [
  {
    key: 'users',
    label: 'Users',
    delegate: 'user',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['username', 'fullName', 'phone', 'email'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'telegramId', label: 'Telegram ID', type: 'bigint', list: true },
      { name: 'username', label: 'Username', type: 'string', list: true },
      { name: 'fullName', label: 'Full name', type: 'string', list: true },
      { name: 'phone', label: 'Phone', type: 'string', list: true },
      { name: 'email', label: 'Email', type: 'string', list: true },
      { name: 'status', label: 'Status', type: 'enum', required: true, list: true, options: enumOptions(UserStatus) },
      { name: 'roleId', label: 'Role', type: 'relation', virtual: true, create: true, update: true, list: false, relation: { entityKey: 'roles', labelField: 'name' } },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'roles',
    label: 'Roles',
    delegate: 'role',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['name'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'name', label: 'Name', type: 'enum', list: true, options: enumOptions(RoleName) },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'categories',
    label: 'Categories',
    delegate: 'category',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['name', 'icon'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'name', label: 'Name', type: 'string', required: true, list: true },
      { name: 'icon', label: 'Icon', type: 'string', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'user-roles',
    label: 'User roles',
    delegate: 'userRole',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'roleId', label: 'Role', type: 'relation', required: true, list: true, relation: { entityKey: 'roles', labelField: 'name' } },
      { name: 'createdAt', label: 'Created at', type: 'date', readonly: true, list: true, create: false, update: false },
      { name: 'updatedAt', label: 'Updated at', type: 'date', readonly: true, list: true, create: false, update: false },
      softDeleteField,
    ],
  },
  {
    key: 'products',
    label: 'Products',
    delegate: 'product',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['code', 'name'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'code', label: 'Code', type: 'string', list: true },
      { name: 'name', label: 'Name', type: 'string', list: true },
      { name: 'description', label: 'Description', type: 'text', list: false },
      { name: 'categoryId', label: 'Category', type: 'relation', list: true, relation: { entityKey: 'categories', labelField: 'name' } },
      { name: 'imageUrl', label: 'Image URL', type: 'string', list: false },
      { name: 'isActive', label: 'Active', type: 'boolean', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'product-variants',
    label: 'Product variants',
    delegate: 'productVariant',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['name'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'productId', label: 'Product', type: 'relation', required: true, list: true, relation: { entityKey: 'products', labelField: 'name' } },
      { name: 'name', label: 'Name', type: 'string', list: true },
      { name: 'durationDays', label: 'Duration days', type: 'int', list: true },
      { name: 'sellPrice', label: 'Sell price', type: 'decimal', list: true },
      { name: 'warrantyDays', label: 'Warranty days', type: 'int', list: true },
      { name: 'active', label: 'Active', type: 'boolean', list: true },
      { name: 'averageRating', label: 'Average rating', type: 'decimal', readonly: true, list: true, create: false, update: false },
      { name: 'reviewCount', label: 'Reviews', type: 'int', readonly: true, list: true, create: false, update: false },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'coupons',
    label: 'Marketing - Coupons',
    delegate: 'coupon',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['code', 'name', 'description'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'code', label: 'Code', type: 'string', required: true, list: true },
      { name: 'name', label: 'Name', type: 'string', required: true, list: true },
      { name: 'description', label: 'Description', type: 'text', list: false },
      { name: 'discountType', label: 'Discount type', type: 'enum', required: true, list: true, options: enumOptions(DiscountType) },
      { name: 'discountValue', label: 'Discount value', type: 'decimal', required: true, list: true },
      { name: 'maxDiscount', label: 'Max discount', type: 'decimal', list: true },
      { name: 'minOrderAmount', label: 'Min order amount', type: 'decimal', list: true },
      { name: 'usageLimit', label: 'Usage limit', type: 'int', list: true },
      { name: 'usedCount', label: 'Used', type: 'int', readonly: true, list: true, create: false, update: false },
      { name: 'startsAt', label: 'Starts at', type: 'date', list: true },
      { name: 'endsAt', label: 'Ends at', type: 'date', list: true },
      { name: 'isActive', label: 'Active', type: 'boolean', list: true },
      { name: 'createdBy', label: 'Created by', type: 'relation', list: false, relation: { entityKey: 'users', labelField: 'email' } },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'coupon-products',
    label: 'Marketing - Coupon products',
    delegate: 'couponProduct',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'couponId', label: 'Coupon', type: 'relation', required: true, list: true, relation: { entityKey: 'coupons', labelField: 'code' } },
      { name: 'productVariantId', label: 'Product variant', type: 'relation', required: true, list: true, relation: { entityKey: 'product-variants', labelField: 'name' } },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'coupon-users',
    label: 'Marketing - Coupon users',
    delegate: 'couponUser',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'couponId', label: 'Coupon', type: 'relation', required: true, list: true, relation: { entityKey: 'coupons', labelField: 'code' } },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'coupon-usages',
    label: 'Marketing - Coupon usages',
    delegate: 'couponUsage',
    softDelete: true,
    defaultSort: 'usedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'couponId', label: 'Coupon', type: 'relation', readonly: true, list: true, create: false, update: false, relation: { entityKey: 'coupons', labelField: 'code' } },
      { name: 'userId', label: 'User', type: 'relation', readonly: true, list: true, create: false, update: false, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'orderId', label: 'Order', type: 'relation', readonly: true, list: true, create: false, update: false, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'discountAmount', label: 'Discount amount', type: 'decimal', readonly: true, list: true, create: false, update: false },
      { name: 'usedAt', label: 'Used at', type: 'date', readonly: true, list: true, create: false, update: false },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'inventories',
    label: 'Inventories',
    delegate: 'inventory',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['accountEmail'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'variantId', label: 'Variant', type: 'relation', required: true, list: true, relation: { entityKey: 'product-variants', labelField: 'name' } },
      { name: 'accountEmail', label: 'Account email', type: 'string', list: true },
      { name: 'encryptedPassword', label: 'Password', type: 'text', list: false },
      { name: 'metadata', label: 'Metadata', type: 'json', list: false },
      { name: 'status', label: 'Status', type: 'enum', required: true, list: true, options: enumOptions(InventoryStatus) },
      { name: 'reservedBy', label: 'Reserved by', type: 'relation', list: false, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'reservedAt', label: 'Reserved at', type: 'date', list: false },
      { name: 'reservedUntil', label: 'Reserved until', type: 'date', readonly: true, list: false, create: false, update: false },
      { name: 'reservedOrderId', label: 'Reserved order', type: 'relation', readonly: true, list: false, create: false, update: false, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'deliveredAt', label: 'Delivered at', type: 'date', list: false },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'orders',
    label: 'Orders',
    delegate: 'order',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['orderNo'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'orderNo', label: 'Order no', type: 'string', list: true },
      { name: 'userId', label: 'User', type: 'relation', list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'subtotal', label: 'Subtotal', type: 'decimal', list: true },
      { name: 'discount', label: 'Discount', type: 'decimal', list: true },
      { name: 'totalAmount', label: 'Total amount', type: 'decimal', list: true },
      { name: 'couponId', label: 'Coupon', type: 'relation', list: true, relation: { entityKey: 'coupons', labelField: 'code' } },
      { name: 'status', label: 'Status', type: 'enum', list: true, options: enumOptions(OrderStatus) },
      { name: 'paymentStatus', label: 'Payment status', type: 'enum', list: true, options: enumOptions(PaymentStatus) },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'order-items',
    label: 'Order items',
    delegate: 'orderItem',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'orderId', label: 'Order', type: 'relation', list: true, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'variantId', label: 'Variant', type: 'relation', list: true, relation: { entityKey: 'product-variants', labelField: 'name' } },
      { name: 'inventoryId', label: 'Inventory', type: 'relation', list: true, relation: { entityKey: 'inventories', labelField: 'accountEmail' } },
      { name: 'quantity', label: 'Quantity', type: 'int', list: true },
      { name: 'unitPrice', label: 'Unit price', type: 'decimal', list: true },
      { name: 'totalPrice', label: 'Total price', type: 'decimal', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'payments',
    label: 'Payments',
    delegate: 'payment',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['provider', 'transactionNo', 'paymentContent'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'orderId', label: 'Order', type: 'relation', list: true, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'provider', label: 'Provider', type: 'enum', list: true, options: [
        { label: 'BANKING_QR', value: 'BANKING_QR' },
        { label: 'MOMO', value: 'MOMO' },
        { label: 'ZALOPAY', value: 'ZALOPAY' },
        { label: 'VNPAY', value: 'VNPAY' },
      ] },
      { name: 'amount', label: 'Amount', type: 'decimal', list: true },
      { name: 'transactionNo', label: 'Transaction no', type: 'string', list: true },
      { name: 'paymentContent', label: 'Payment content', type: 'string', list: false },
      { name: 'qrContent', label: 'QR content', type: 'text', list: false },
      { name: 'status', label: 'Status', type: 'enum', list: true, options: enumOptions(PaymentStatus) },
      { name: 'paidAt', label: 'Paid at', type: 'date', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'deliveries',
    label: 'Deliveries',
    delegate: 'delivery',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'orderItemId', label: 'Order item', type: 'relation', list: true, relation: { entityKey: 'order-items', labelField: 'id' } },
      { name: 'inventoryId', label: 'Inventory', type: 'relation', list: true, relation: { entityKey: 'inventories', labelField: 'accountEmail' } },
      { name: 'deliveryContent', label: 'Delivery content', type: 'text', list: false },
      { name: 'deliveredAt', label: 'Delivered at', type: 'date', list: true },
      { name: 'status', label: 'Status', type: 'enum', list: true, options: enumOptions(DeliveryStatus) },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'tickets',
    label: 'Tickets',
    delegate: 'ticket',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['subject', 'content'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'orderId', label: 'Order', type: 'relation', list: true, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'subject', label: 'Subject', type: 'string', required: true, list: true },
      { name: 'content', label: 'Content', type: 'text', required: true, list: false },
      { name: 'status', label: 'Status', type: 'enum', list: true, options: enumOptions(TicketStatus) },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'reviews',
    label: 'Feedback - Reviews',
    delegate: 'review',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['comment'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'orderId', label: 'Order', type: 'relation', required: true, list: true, relation: { entityKey: 'orders', labelField: 'orderNo' } },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'productVariantId', label: 'Product variant', type: 'relation', required: true, list: true, relation: { entityKey: 'product-variants', labelField: 'name' } },
      { name: 'rating', label: 'Rating', type: 'int', required: true, list: true },
      { name: 'comment', label: 'Comment', type: 'text', list: true },
      { name: 'isHidden', label: 'Hidden', type: 'boolean', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'notifications',
    label: 'Notifications',
    delegate: 'notification',
    softDelete: true,
    defaultSort: 'updatedAt',
    searchableFields: ['type', 'title', 'content'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'type', label: 'Type', type: 'enum', list: true, options: enumOptions(NotificationType) },
      { name: 'title', label: 'Title', type: 'string', required: true, list: true },
      { name: 'content', label: 'Content', type: 'text', required: true, list: false },
      { name: 'isRead', label: 'Read', type: 'boolean', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'refresh-tokens',
    label: 'Refresh tokens',
    delegate: 'refreshToken',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'tokenHash', label: 'Token hash', type: 'text', required: true, list: false },
      { name: 'expiredAt', label: 'Expired at', type: 'date', required: true, list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'admin-login-tokens',
    label: 'Admin login tokens',
    delegate: 'adminLoginToken',
    softDelete: true,
    defaultSort: 'updatedAt',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', required: true, list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'tokenHash', label: 'Token hash', type: 'text', required: true, list: false },
      { name: 'status', label: 'Status', type: 'enum', list: true, options: enumOptions(AdminLoginTokenStatus) },
      { name: 'expiredAt', label: 'Expired at', type: 'date', required: true, list: true },
      { name: 'usedAt', label: 'Used at', type: 'date', list: true },
      ...timestamps,
      softDeleteField,
    ],
  },
  {
    key: 'audit-logs',
    label: 'Audit logs',
    delegate: 'auditLog',
    softDelete: true,
    defaultSort: 'createdAt',
    searchableFields: ['entityName', 'action'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'actorId', label: 'Actor', type: 'relation', list: true, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'entityName', label: 'Entity name', type: 'string', required: true, list: true },
      { name: 'entityId', label: 'Entity ID', type: 'uuid', list: true },
      { name: 'action', label: 'Action', type: 'enum', required: true, list: true, options: enumOptions(AuditAction) },
      { name: 'oldData', label: 'Old data', type: 'json', list: false },
      { name: 'newData', label: 'New data', type: 'json', list: false },
      { name: 'ipAddress', label: 'IP address', type: 'string', list: false },
      { name: 'userAgent', label: 'User agent', type: 'string', list: false },
      { name: 'createdAt', label: 'Created at', type: 'date', readonly: true, list: true, create: false, update: false },
      { name: 'updatedAt', label: 'Updated at', type: 'date', readonly: true, list: true, create: false, update: false },
      softDeleteField,
    ],
  },
  {
    key: 'activity-logs',
    label: 'Activity logs',
    delegate: 'activityLog',
    softDelete: true,
    defaultSort: 'createdAt',
    searchableFields: ['entityName', 'type'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'userId', label: 'User', type: 'relation', readonly: true, list: true, create: false, update: false, relation: { entityKey: 'users', labelField: 'email' } },
      { name: 'type', label: 'Type', type: 'enum', readonly: true, list: true, create: false, update: false, options: enumOptions(ActivityLogType) },
      { name: 'entityName', label: 'Entity name', type: 'string', readonly: true, list: true, create: false, update: false },
      { name: 'entityId', label: 'Entity ID', type: 'uuid', readonly: true, list: true, create: false, update: false },
      { name: 'metadata', label: 'Metadata', type: 'json', readonly: true, list: false, create: false, update: false },
      { name: 'createdAt', label: 'Created at', type: 'date', readonly: true, list: true, create: false, update: false },
      { name: 'updatedAt', label: 'Updated at', type: 'date', readonly: true, list: true, create: false, update: false },
      softDeleteField,
    ],
  },
];

export const ADMIN_ENTITY_MAP = new Map(
  ADMIN_ENTITIES.map((entity) => [entity.key, entity]),
);
