import {
  KieuPhuongThucGiaoHang,
  LoaiAudit,
  LoaiGiamGia,
  LoaiNguonGiaoHang,
  LoaiThongBao,
  NhaCungCapKenhNhanViec,
  NhaCungCapTrangThai,
  TrangThaiChung,
  TrangThaiDonHang,
  TrangThaiGiaoHang,
  TrangThaiLienKetNhaCungCap,
  TrangThaiNguoiDung,
  TrangThaiTaiNguyen,
  TrangThaiThanhToan,
  TrangThaiTicket,
  TrangThaiYeuCauNhaCungCap,
  VaiTroHeThong,
} from '../../../generated/prisma/client.js';
import { AdminEntityConfig, AdminEnumOption } from '../interfaces/admin-crud.interface';

const enumOptions = (source: Record<string, string | number>): AdminEnumOption[] =>
  Object.entries(source)
    .filter(([label]) => Number.isNaN(Number(label)))
    .map(([label, value]) => ({ label, value }));

const timestamps = [
  { name: 'taoLuc', label: 'Tạo lúc', type: 'date' as const, readonly: true, list: true, create: false, update: false },
  { name: 'capNhatLuc', label: 'Cập nhật lúc', type: 'date' as const, readonly: true, list: true, create: false, update: false },
];

const daXoaField = {
  name: 'daXoa',
  label: 'Đã xóa',
  type: 'boolean' as const,
  readonly: true,
  hidden: true,
  create: false,
  update: false,
};

export const ADMIN_ENTITIES: AdminEntityConfig[] = [
  {
    key: 'nguoi-dung',
    label: 'Người dùng',
    delegate: 'nguoiDung',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['username', 'hoTen', 'soDienThoai', 'email'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'telegramId', label: 'Telegram ID', type: 'bigint', list: true },
      { name: 'username', label: 'Username', type: 'string', list: true },
      { name: 'hoTen', label: 'Họ tên', type: 'string', list: true },
      { name: 'soDienThoai', label: 'Số điện thoại', type: 'string', list: true },
      { name: 'email', label: 'Email', type: 'string', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiNguoiDung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'vai-tro',
    label: 'Vai trò',
    delegate: 'vaiTro',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['ten'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'ten', label: 'Tên vai trò', type: 'enum', required: true, list: true, options: enumOptions(VaiTroHeThong) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'loai-san-pham',
    label: 'Loại sản phẩm',
    delegate: 'loaiSanPham',
    softDelete: true,
    defaultSort: 'thuTu',
    searchableFields: ['maLoai', 'tenLoai', 'moTa'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'maLoai', label: 'Mã loại', type: 'string', required: true, list: true },
      { name: 'tenLoai', label: 'Tên loại', type: 'string', required: true, list: true },
      { name: 'moTa', label: 'Mô tả', type: 'text', list: false },
      { name: 'icon', label: 'Icon', type: 'string', list: true },
      { name: 'thuTu', label: 'Thứ tự', type: 'int', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'san-pham',
    label: 'Sản phẩm',
    delegate: 'sanPham',
    softDelete: true,
    defaultSort: 'thuTu',
    searchableFields: ['maSanPham', 'tenSanPham', 'moTa'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'loaiId', label: 'Loại sản phẩm', type: 'relation', required: true, list: true, relation: { entityKey: 'loai-san-pham', labelField: 'tenLoai' } },
      { name: 'maSanPham', label: 'Mã sản phẩm', type: 'string', required: true, list: true },
      { name: 'tenSanPham', label: 'Tên sản phẩm', type: 'string', required: true, list: true },
      { name: 'moTa', label: 'Mô tả', type: 'text', list: false },
      { name: 'anhDaiDien', label: 'Ảnh đại diện', type: 'image', list: false },
      { name: 'thuTu', label: 'Thứ tự', type: 'int', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'goi-dich-vu',
    label: 'Gói dịch vụ',
    delegate: 'goiDichVu',
    softDelete: true,
    defaultSort: 'thuTu',
    searchableFields: ['maGoi', 'tenGoi', 'moTa'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'sanPhamId', label: 'Sản phẩm', type: 'relation', required: true, list: true, relation: { entityKey: 'san-pham', labelField: 'tenSanPham' } },
      { name: 'maGoi', label: 'Mã gói', type: 'string', required: true, list: true },
      { name: 'tenGoi', label: 'Tên gói', type: 'string', required: true, list: true },
      { name: 'moTa', label: 'Mô tả', type: 'text', list: false },
      { name: 'thoiHanNgay', label: 'Thời hạn ngày', type: 'int', list: true },
      { name: 'baoHanhNgay', label: 'Bảo hành ngày', type: 'int', list: true },
      { name: 'giaBan', label: 'Giá bán', type: 'decimal', required: true, list: true },
      { name: 'giaVonDuKien', label: 'Giá vốn dự kiến', type: 'decimal', list: true },
      { name: 'tonHienThi', label: 'Tồn hiển thị', type: 'int', list: true },
      { name: 'choPhepMua', label: 'Cho phép mua', type: 'boolean', list: true },
      { name: 'thuTu', label: 'Thứ tự', type: 'int', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'phuong-thuc-giao-hang',
    label: 'Phương thức giao hàng',
    delegate: 'phuongThucGiaoHang',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['maPhuongThuc', 'tenPhuongThuc', 'moTa'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'maPhuongThuc', label: 'Mã phương thức', type: 'string', required: true, list: true },
      { name: 'tenPhuongThuc', label: 'Tên phương thức', type: 'string', required: true, list: true },
      { name: 'kieu', label: 'Kiểu xử lý', type: 'enum', required: true, list: true, options: enumOptions(KieuPhuongThucGiaoHang) },
      { name: 'moTa', label: 'Mô tả', type: 'text', list: false },
      { name: 'cauHinhMacDinh', label: 'Cấu hình mặc định', type: 'json', list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'goi-phuong-thuc',
    label: 'Gói - phương thức',
    delegate: 'goiPhuongThucGiaoHang',
    softDelete: true,
    defaultSort: 'uuTien',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'goiDichVuId', label: 'Gói dịch vụ', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-dich-vu', labelField: 'tenGoi' } },
      { name: 'phuongThucId', label: 'Phương thức', type: 'relation', required: true, list: true, relation: { entityKey: 'phuong-thuc-giao-hang', labelField: 'tenPhuongThuc' } },
      { name: 'uuTien', label: 'Ưu tiên', type: 'int', list: true },
      { name: 'laMacDinh', label: 'Mặc định', type: 'boolean', list: true },
      { name: 'tuDongGanSupplier', label: 'Tự gán supplier', type: 'boolean', list: true },
      { name: 'cauHinh', label: 'Cấu hình', type: 'json', list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'nha-cung-cap',
    label: 'Nhà cung cấp',
    delegate: 'nhaCungCap',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['tenHienThi', 'usernameTelegram', 'soDienThoai', 'email'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nguoiDungId', label: 'Người dùng liên kết', type: 'relation', list: false, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'telegramId', label: 'Telegram ID', type: 'bigint', list: true },
      { name: 'usernameTelegram', label: 'Username Telegram', type: 'string', list: true },
      { name: 'tenHienThi', label: 'Tên hiển thị', type: 'string', required: true, list: true },
      { name: 'soDienThoai', label: 'Số điện thoại', type: 'string', list: true },
      { name: 'email', label: 'Email', type: 'string', list: true },
      { name: 'ghiChu', label: 'Ghi chú', type: 'text', list: false },
      { name: 'kenhNhanViec', label: 'Kênh nhận việc', type: 'enum', list: true, options: enumOptions(NhaCungCapKenhNhanViec) },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(NhaCungCapTrangThai) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'link-moi-nha-cung-cap',
    label: 'Link mời nhà cung cấp',
    delegate: 'lienKetNhaCungCap',
    defaultSort: 'capNhatLuc',
    searchableFields: ['maToken', 'tenMoi', 'ghiChu'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nhaCungCapId', label: 'Nhà cung cấp', type: 'relation', list: true, relation: { entityKey: 'nha-cung-cap', labelField: 'tenHienThi' } },
      { name: 'maToken', label: 'Token/link', type: 'string', required: false, list: true },
      { name: 'tenMoi', label: 'Tên mời', type: 'string', list: true },
      { name: 'ghiChu', label: 'Ghi chú', type: 'text', list: false },
      { name: 'telegramIdDaGan', label: 'Telegram đã gán', type: 'bigint', list: true },
      { name: 'hetHanLuc', label: 'Hết hạn lúc', type: 'date', list: true },
      { name: 'dungLuc', label: 'Dùng lúc', type: 'date', readonly: true, list: true, create: false, update: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiLienKetNhaCungCap) },
      ...timestamps,
    ],
  },
  {
    key: 'supplier-goi-dich-vu',
    label: 'Supplier - gói dịch vụ',
    delegate: 'nhaCungCapGoiDichVu',
    softDelete: true,
    defaultSort: 'uuTien',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nhaCungCapId', label: 'Nhà cung cấp', type: 'relation', required: true, list: true, relation: { entityKey: 'nha-cung-cap', labelField: 'tenHienThi' } },
      { name: 'goiDichVuId', label: 'Gói dịch vụ', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-dich-vu', labelField: 'tenGoi' } },
      { name: 'goiPhuongThucId', label: 'Gói - phương thức', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-phuong-thuc', labelField: 'id' } },
      { name: 'giaVon', label: 'Giá vốn', type: 'decimal', list: true },
      { name: 'soLuongCoTheNhan', label: 'Số lượng có thể nhận', type: 'int', list: true },
      { name: 'soLuongDangGiu', label: 'Số lượng đang giữ', type: 'int', readonly: true, list: true, create: false, update: false },
      { name: 'thoiGianXuLyPhut', label: 'Thời gian xử lý phút', type: 'int', list: true },
      { name: 'tyLeThanhCong', label: 'Tỷ lệ thành công', type: 'decimal', list: true },
      { name: 'uuTien', label: 'Ưu tiên', type: 'int', list: true },
      { name: 'cauHinh', label: 'Cấu hình', type: 'json', list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'tai-nguyen-giao-hang',
    label: 'Tài nguyên giao hàng',
    delegate: 'taiNguyenGiaoHang',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['maTaiNguyen'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'goiDichVuId', label: 'Gói dịch vụ', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-dich-vu', labelField: 'tenGoi' } },
      { name: 'goiPhuongThucId', label: 'Gói - phương thức', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-phuong-thuc', labelField: 'id' } },
      { name: 'maTaiNguyen', label: 'Mã tài nguyên', type: 'string', list: true },
      { name: 'duLieuMaHoa', label: 'Dữ liệu mã hóa', type: 'text', list: false },
      { name: 'duLieuCongKhai', label: 'Dữ liệu công khai', type: 'json', list: false },
      { name: 'soLanDungToiDa', label: 'Số lần dùng tối đa', type: 'int', list: true },
      { name: 'soLanDaDung', label: 'Số lần đã dùng', type: 'int', readonly: true, list: true, create: false, update: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiTaiNguyen) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'don-hang',
    label: 'Đơn hàng',
    delegate: 'donHang',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['maDonHang'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'maDonHang', label: 'Mã đơn hàng', type: 'string', list: true },
      { name: 'nguoiDungId', label: 'Người dùng', type: 'relation', list: true, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'tamTinh', label: 'Tạm tính', type: 'decimal', list: true },
      { name: 'giamGia', label: 'Giảm giá', type: 'decimal', list: true },
      { name: 'tongTien', label: 'Tổng tiền', type: 'decimal', list: true },
      { name: 'maGiamGiaId', label: 'Mã giảm giá', type: 'relation', list: true, relation: { entityKey: 'ma-giam-gia', labelField: 'ma' } },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiDonHang) },
      { name: 'trangThaiThanhToan', label: 'Trạng thái thanh toán', type: 'enum', list: true, options: enumOptions(TrangThaiThanhToan) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'chi-tiet-don-hang',
    label: 'Chi tiết đơn hàng',
    delegate: 'chiTietDonHang',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'donHangId', label: 'Đơn hàng', type: 'relation', list: true, relation: { entityKey: 'don-hang', labelField: 'maDonHang' } },
      { name: 'goiDichVuId', label: 'Gói dịch vụ', type: 'relation', list: true, relation: { entityKey: 'goi-dich-vu', labelField: 'tenGoi' } },
      { name: 'goiPhuongThucId', label: 'Gói - phương thức', type: 'relation', list: true, relation: { entityKey: 'goi-phuong-thuc', labelField: 'id' } },
      { name: 'soLuong', label: 'Số lượng', type: 'int', list: true },
      { name: 'donGia', label: 'Đơn giá', type: 'decimal', list: true },
      { name: 'thanhTien', label: 'Thành tiền', type: 'decimal', list: true },
      { name: 'duLieuKhachNhap', label: 'Dữ liệu khách nhập', type: 'json', list: false },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'thanh-toan',
    label: 'Thanh toán',
    delegate: 'thanhToan',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['nhaCungCapThanhToan', 'maGiaoDich', 'noiDungThanhToan'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'donHangId', label: 'Đơn hàng', type: 'relation', list: true, relation: { entityKey: 'don-hang', labelField: 'maDonHang' } },
      { name: 'nhaCungCapThanhToan', label: 'Cổng thanh toán', type: 'string', list: true },
      { name: 'soTien', label: 'Số tiền', type: 'decimal', list: true },
      { name: 'maGiaoDich', label: 'Mã giao dịch', type: 'string', list: true },
      { name: 'noiDungThanhToan', label: 'Nội dung thanh toán', type: 'string', list: true },
      { name: 'duLieuQr', label: 'Dữ liệu QR', type: 'json', list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiThanhToan) },
      { name: 'thanhToanLuc', label: 'Thanh toán lúc', type: 'date', list: true },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'yeu-cau-nha-cung-cap',
    label: 'Yêu cầu nhà cung cấp',
    delegate: 'yeuCauNhaCungCap',
    defaultSort: 'capNhatLuc',
    searchableFields: ['maYeuCau', 'ghiChu'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'chiTietDonHangId', label: 'Chi tiết đơn', type: 'relation', list: true, relation: { entityKey: 'chi-tiet-don-hang', labelField: 'id' } },
      { name: 'nhaCungCapId', label: 'Nhà cung cấp', type: 'relation', list: true, relation: { entityKey: 'nha-cung-cap', labelField: 'tenHienThi' } },
      { name: 'maYeuCau', label: 'Mã yêu cầu', type: 'string', required: true, list: true },
      { name: 'soLuong', label: 'Số lượng', type: 'int', list: true },
      { name: 'duLieuGui', label: 'Dữ liệu gửi', type: 'json', list: false },
      { name: 'duLieuPhanHoi', label: 'Dữ liệu phản hồi', type: 'json', list: false },
      { name: 'tokenForm', label: 'Token form', type: 'string', list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiYeuCauNhaCungCap) },
      { name: 'ghiChu', label: 'Ghi chú', type: 'text', list: false },
      ...timestamps,
    ],
  },
  {
    key: 'giao-hang',
    label: 'Giao hàng',
    delegate: 'giaoHang',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'chiTietDonHangId', label: 'Chi tiết đơn', type: 'relation', list: true, relation: { entityKey: 'chi-tiet-don-hang', labelField: 'id' } },
      { name: 'taiNguyenId', label: 'Tài nguyên', type: 'relation', list: true, relation: { entityKey: 'tai-nguyen-giao-hang', labelField: 'maTaiNguyen' } },
      { name: 'yeuCauNhaCungCapId', label: 'Yêu cầu NCC', type: 'relation', list: true, relation: { entityKey: 'yeu-cau-nha-cung-cap', labelField: 'maYeuCau' } },
      { name: 'nguonGiaoHang', label: 'Nguồn giao', type: 'enum', list: true, options: enumOptions(LoaiNguonGiaoHang) },
      { name: 'noiDungGiao', label: 'Nội dung giao', type: 'text', list: false },
      { name: 'duLieuGiao', label: 'Dữ liệu giao', type: 'json', list: false },
      { name: 'metadata', label: 'Metadata', type: 'json', list: false },
      { name: 'giaoLuc', label: 'Giao lúc', type: 'date', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiGiaoHang) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'ma-giam-gia',
    label: 'Mã giảm giá',
    delegate: 'maGiamGia',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['ma', 'ten', 'moTa'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'ma', label: 'Mã', type: 'string', required: true, list: true },
      { name: 'ten', label: 'Tên', type: 'string', required: true, list: true },
      { name: 'moTa', label: 'Mô tả', type: 'text', list: false },
      { name: 'loaiGiamGia', label: 'Loại giảm giá', type: 'enum', required: true, list: true, options: enumOptions(LoaiGiamGia) },
      { name: 'giaTriGiam', label: 'Giá trị giảm', type: 'decimal', required: true, list: true },
      { name: 'giamToiDa', label: 'Giảm tối đa', type: 'decimal', list: true },
      { name: 'donToiThieu', label: 'Đơn tối thiểu', type: 'decimal', list: true },
      { name: 'gioiHanLuotDung', label: 'Giới hạn lượt dùng', type: 'int', list: true },
      { name: 'soLuotDaDung', label: 'Đã dùng', type: 'int', readonly: true, list: true, create: false, update: false },
      { name: 'batDauLuc', label: 'Bắt đầu lúc', type: 'date', list: true },
      { name: 'ketThucLuc', label: 'Kết thúc lúc', type: 'date', list: true },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiChung) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'ticket-ho-tro',
    label: 'Ticket hỗ trợ',
    delegate: 'ticketHoTro',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['tieuDe', 'noiDung'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nguoiDungId', label: 'Người dùng', type: 'relation', required: true, list: true, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'donHangId', label: 'Đơn hàng', type: 'relation', list: true, relation: { entityKey: 'don-hang', labelField: 'maDonHang' } },
      { name: 'tieuDe', label: 'Tiêu đề', type: 'string', required: true, list: true },
      { name: 'noiDung', label: 'Nội dung', type: 'text', required: true, list: false },
      { name: 'trangThai', label: 'Trạng thái', type: 'enum', list: true, options: enumOptions(TrangThaiTicket) },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'danh-gia',
    label: 'Đánh giá',
    delegate: 'danhGia',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['noiDung'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'donHangId', label: 'Đơn hàng', type: 'relation', required: true, list: true, relation: { entityKey: 'don-hang', labelField: 'maDonHang' } },
      { name: 'nguoiDungId', label: 'Người dùng', type: 'relation', required: true, list: true, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'goiDichVuId', label: 'Gói dịch vụ', type: 'relation', required: true, list: true, relation: { entityKey: 'goi-dich-vu', labelField: 'tenGoi' } },
      { name: 'soSao', label: 'Số sao', type: 'int', required: true, list: true },
      { name: 'noiDung', label: 'Nội dung', type: 'text', list: true },
      { name: 'biAn', label: 'Bị ẩn', type: 'boolean', list: true },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'thong-bao',
    label: 'Thông báo',
    delegate: 'thongBao',
    softDelete: true,
    defaultSort: 'capNhatLuc',
    searchableFields: ['tieuDe', 'noiDung'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nguoiDungId', label: 'Người dùng', type: 'relation', required: true, list: true, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'loai', label: 'Loại', type: 'enum', list: true, options: enumOptions(LoaiThongBao) },
      { name: 'tieuDe', label: 'Tiêu đề', type: 'string', required: true, list: true },
      { name: 'noiDung', label: 'Nội dung', type: 'text', required: true, list: false },
      { name: 'daDoc', label: 'Đã đọc', type: 'boolean', list: true },
      ...timestamps,
      daXoaField,
    ],
  },
  {
    key: 'audit-log',
    label: 'Nhật ký hệ thống',
    delegate: 'auditLog',
    softDelete: true,
    defaultSort: 'taoLuc',
    searchableFields: ['tenBang', 'hanhDong'],
    fields: [
      { name: 'id', label: 'ID', type: 'uuid', readonly: true, list: false, create: false, update: false },
      { name: 'nguoiThucHienId', label: 'Người thực hiện', type: 'relation', list: true, relation: { entityKey: 'nguoi-dung', labelField: 'hoTen' } },
      { name: 'tenBang', label: 'Tên bảng', type: 'string', required: true, list: true },
      { name: 'banGhiId', label: 'Bản ghi ID', type: 'uuid', list: true },
      { name: 'hanhDong', label: 'Hành động', type: 'enum', required: true, list: true, options: enumOptions(LoaiAudit) },
      { name: 'duLieuCu', label: 'Dữ liệu cũ', type: 'json', list: false },
      { name: 'duLieuMoi', label: 'Dữ liệu mới', type: 'json', list: false },
      { name: 'ip', label: 'IP', type: 'string', list: false },
      { name: 'userAgent', label: 'User agent', type: 'string', list: false },
      ...timestamps,
      daXoaField,
    ],
  },
];

export const ADMIN_ENTITY_MAP = new Map(ADMIN_ENTITIES.map((entity) => [entity.key, entity]));
