app = "ai-store-api-hieuhv203"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8903"
  PAYOS_API_BASE_URL = "https://api-merchant.payos.vn"
  PAYOS_PAYMENT_DESCRIPTION_PREFIX = "AI Store"

[http_service]
  internal_port = 8903
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
